name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run:
        echo "${secrets.PUSH_TOKEN}" | docker login --username lilja --password-stdin;
        docker build . --file Dockerfile --tag lilja/blog:${GITHUB_SHA};
        docker push lilja/blog
          
