name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Login to docker hub
      run: echo "${{ secrets.PUSH_TOKEN }}" | docker login --username lilja --password-stdin;
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag lilja/blog:${GITHUB_SHA};
    - name: Push image to docker hub
      run: docker push lilja/blog
          
